### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by pjbish** [skorokithakis/netproxy#6]
I've followed the instructions, and the commands aren't working for me. I've managed to get to the last step by changing a few of them, but this one particular isn't working:

docker run -p 53:53/udp -p 80:80 -p 443:443 -d skorokithakis/netproxy

I can VPN to the box, and see US Netflix, but get a proxy error when I try to watch

**Comment by pjbish** [comment]
Here's the error

docker run -p 53:53/udp -p 80:80 -p 443:443 -d skorokithakis/netproxy
Unable to find image 'skorokithakis/netproxy:latest' locally
Pulling repository docker.io/skorokithakis/netproxy
Error: image skorokithakis/netproxy:latest not found

**Comment by skorokithakis** [comment]
Did you tag the image when building?

**Comment by pjbish** [comment]
Hi , Thanks for responding.
The tag command doesn't work.

Here's how far I get:

Install docker & Git . All OK

Clone the repository on my Ubuntu 14.04 . All OK

cd netproxy
python preprocess.py

Both work OK.

docker build - t skorokithakis/netproxy  fails. Returns the following error 

**root@ustestla:~/netproxy# docker build - t skorokithakis/netproxy
docker: "build" requires 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile**

If I go back to root, I can run this though:

docker build netproxy

It work, but displays some warnings / errors

**Comment by pjbish** [comment]
Apologies if this is a newbie error. I'm new to docker.

**Comment by skorokithakis** [comment]
Try:

`docker build - t skorokithakis/netproxy .`

**Comment by pjbish** [comment]
Still not working

root@ustestla:~# docker build - t skorokithakis/netproxy .
docker: "build" requires 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

Should I be running this from the net proxy directory ?

**Comment by skorokithakis** [comment]
Yes, of course. What's your docker version?

**Comment by pjbish** [comment]
Fails with he same error from netproxy dir.

oot@ustestla:~/netproxy# docker.io version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

**Comment by skorokithakis** [comment]
Ah, there's a space between `-` and `t`. There should not be a space between `-` and `t`.

**Comment by pjbish** [comment]
Hi Stavros.

Thanks for your help . I managed to get through the setup. 

When I either use the VPS as my DNS or I VPN to it, I can see the US Netflix catalogue fine, but if I try and play anything, I get the proxy error. I'm guessing that the config file hasn't been updated to include the latest settings such as nflxvideo.net.

Where would I find the config file ?

On a separate (but kind of related) subject. The reason that I’m playing with this is that I run a small VPN provider here in Australia. We’ve only been going for a month, but we’re seeing subscribers grow. The majority of our customers use our Service for watching US Netflix.

I’m looking for a developer, who can help us implement a more robust solution than the one that we currently use. I’m also looking to offer DNS as a solution for bypassing the Netflix geoblocking (for smart TVs, apple TV etc). Lastly, I also want to expand our offering to Netflix in other countries (like Singapore, Canada etc) as our customers have asked for it.

So, do you have the skills and capability to develop these types of solutions ? If so, would you be interested in helping us ? We’re still very small, so we don’t have a stack of cash, but I’d be happy to discuss paying for each piece of work as it is delivered.

Check out our site www.vanishedvpn.com http://www.vanishedvpn.com/

Where are you based by the way ? 

Phil
